export const paths = {
  home: () => '/',
  signIn: () => '/signin',
  register: () => '/register',
  explore: () => '/explore',
  events: () => '/events',
  eventsCreate: () => '/events/create',
  eventEdit: (id: string) => `/events/${id}/edit`,
  organizationPage: (id: string) => `/organization/${id}`,
  eventPage: (id: string) => `/events/${id}`,
  quiz: () => '/quiz',
  questionPacks: () => '/question-packs',
  teams: () => '/teams',
  stats: () => '/stats',
  leaderboard: () => '/learderboard',
};
